server:
  port: 8000

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:maildb
    username: sa
    password: sa
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    hibernate:
      ddl-auto: create-drop